# Change these first
owner: NigarumOvum # Your GitHub organization or username, where this repository lives
repo: Site-Monitoring-Svelte # The name of this repository
sites:
  - name: Brealy Portfolio
    url: https://brealypadronrodriguez.vercel.app/
  - name: Neighbordev CR
    url: https://neighbordevcr.com/
   - name: Tecnoelectro Comercio Online
    url: https://tecnoelectrocomercioonline.com/
  - name: Drum Web App
    url: https://nigarumovum.github.io/DrumKit-WebApp/
  - name: Tarotly
    url: https://tarotly-react.vercel.app/
   - name: Notes App
    url: https://notes-react-psi.vercel.app/
  - name: Tripin CR
    url: https://tripincr.vercel.app/
  - name: BookFreak
    url: https://book-freak-react.vercel.app/
  - name: Shopping Cart - React
    url: https://shopping-cart-three-omega.vercel.app/
  - name:  Servicing React 
    url: https://servicing-react.vercel.app/
  - name: NASA Explorer
    url: https://nasa-app-api.vercel.app/
  - name: Expense Tracker
    url: https://expense-tracker-vert.vercel.app/
  - name: Song Lyric Browser
    url: https://lyric-search-eosin.vercel.app/
  - name: Meal Finder
    url: https://meal-finder-sandy.vercel.app/
  - name: Exchange Rate Calculator
    url: https://exchange-rate-tau.vercel.app/
status-website:
  name: Neighbordev CR - Monitoring My Apps
  introTitle: "Monitoring My Web Apps"
  introMessage: Thanks for visit...
