# Change these first
owner: nigarumovum # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
sites:
  - name: Neighbordev CR
    url: https://neighbordevcr.com
  - name: Tecnoelectro
    url: https://tecnoelectrocomercioonline.com
  - name: Skin Thing 
    url: https://skinthingcr.herokuapp.com
  - name: Brealy Portfolio
    url: https://brealy-padron-portfolio-react.vercel.app
  - name: Radion v1 
    url: https://radion-react.vercel.app
  - name: Radion v2
    url: https://radion.vercel.app
  - name: Chat App
    url: https://chat-nodeexpect.herokuapp.com
  - name: MacOS Portfolio
    url: https://mac-os-desktop-app-react.vercel.app
  - name: Tripping CR
    url: https://tripincr.vercel.app
  - name: Tarotly
    url: https://tarotly-react.vercel.app
  - name: BookFreak
    url: https://book-freak-react.vercel.app
  - name: NASA Explorer
    url: https://nasa-app-api.vercel.app
  - name: Expense Tracker
    url: https://expense-tracker-vert.vercel.app
  - name: Song Lyric Browser
    url: https://lyric-search-eosin.vercel.app
  - name: Meal Finder
    url: https://meal-finder-sandy.vercel.app/
  - name: Exchange Rate Calculator
    url: https://exchange-rate-tau.vercel.app/
  - name: WebApps & Games
    url: https://web-apps-games.vercel.app/
        
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#   baseUrl: /Site-Monitoring-Svelte
  name: Neighbordev CR - Monitoring Sites
  introTitle: "Monitoring Web App"
  introMessage: Thanks for visit...
